export const ROUTES = {
  LANDING: "/",
  HOME: "/home",
  LOGIN: "/login",
  CREATEACCOUNT: "/createaccount",
  ADMIN_LOGIN: "/admin",
  ADMIN_HOME: "/admin/home",
  ADMIN_NEW_USER: "/admin/newuser",
  ADMIN_USERS_LIST: "/admin/userslist",
  ADMIN_EDIT_USER: "/admin/:id",
  USERPROFILE: "/userprofile",
  ERROR: "*",
  TRANSACTIONS_LIST: "/transactionslist",
  CHECKIN: "/checkin/:id",
  CREATE_TRANSACTION: "/createtransaction/:id",
  EMPLOYEE_LIST: "/employeelist",
  ADD_EMPLOYEE: "/addemployee",
  EMPLOYEE_PROFILE: "/employeeprofile/:id",
  EDIT_EMPLOYEE: "/editemployee/:id",
  ACTIVITY: "/activity",
  ACTIVITY_DETAIL: "/activitydetail",
};
